apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdata-deployment
  labels:
    app: localdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localdata
  template:
    metadata:
      labels:
        app: localdata
    spec:
      imagePullSecrets:
      - name: repo-key
      containers:
      - name: localdata
        image: yxos/localdata
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: localdata-service
spec:
  selector:
    app: localdata
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31003